            - name: Proof HTML
  # You may pin to the exact commit or the version.
  # uses: anishathalye/proof-html@7dc4ab1eb4b36b12d0012657111b180770867139
  uses: anishathalye/proof-html@v2.1.2
  with:
    # The directory to scan
    directory: 
    # Check whether external anchors exist
    check_external_hash: # optional
    # Validate HTML
    check_html: # optional
    # Validate CSS
    check_css: # optional
    # Check images and URLs in Open Graph metadata
    check_opengraph: # optional
    # Check whether favicons are valid
    check_favicon: # optional
    # Allow images with empty alt tags
    ignore_empty_alt: # optional
    # Allow images with missing alt tags
    ignore_missing_alt: # optional
    # Allow anchors with missing href tags
    allow_missing_href: # optional
    # Require that links use HTTPS
    enforce_https: # optional
    # JSON-encoded map of domains to authorization tokens
    tokens: # optional
    # JSON-encoded map of URL rewrite rules
    swap_urls: # optional
    # Maximum number of concurrent requests
    max_concurrency: # optional
    # HTTP connection timeout
    connect_timeout: # optional
    # HTTP request timeout
    timeout: # optional
    # Newline-separated list of URLs to ignore
    ignore_url: # optional
    # Newline-separated list of URL regexes to ignore
    ignore_url_re: # optional
    # Number of times to retry checking links
    retries: # optional
          
